import turtle
turtle.Screen().bgcolor("orange")
draw=turtle.Turtle()
draw.shape("turtle")
draw.color("red")

draw.forward(100)
draw.left(120)
draw.forward(100)
draw.left(120)
draw.forward(100)
#square

draw.penup()
draw.goto(200,0)
draw.pendown()

draw.forward(100)
draw.left(90)
draw.forward(100)
draw.left(90)
draw.forward(100)
draw.left(90)
draw.forward(100)
draw.left(90)

#rectangle
draw.penup()
draw.goto(200,0)
draw.pendown()
draw.begin_fill()
draw.color("black")
draw.fillcolor("black")
draw.forward(200)
draw.left(90)
draw.forward(100)
draw.left(90)
draw.forward(200)
draw.left(90)
draw.endfill()